---
title: Scales
echo: false
---

# Diatonic

Two octaves of the diatonic scale, to start.

|name                |C|D|E|F|G|A| B| C| D| E| F| G| A| B|
|--------------------|-|-|-|-|-|-|--|--|--|--|--|--|--|--|
|scale degree        |1|2|3|4|5|6| 7| 1| 2| 3| 4| 5| 6| 7|
|semitones from root |0|2|4|5|7|9|11|12|14|16|17|19|21|23|

```{ojs}
viewof play = scaleButton([0, 2, 4, 5, 7, 9, 11, 12]);
```

## Mode

When a "scale" is given by starting at a different scale degree of another scale, it's not called a scale: it's called a "mode".

The diatonic scale has 7 distinct modes, each corresponding to what you get if you start a different scale degree.

### "Minor"

The "minor" scale is actually the sixth-degree mode of the diatonic. We start on A and subtract 9 semitones to get back to the root:

|scale degree        |1| 2| 3| 4| 5| 6| 7|
|--------------------|-|--|--|--|--|--|--|
|starting on A       |9|11|12|14|16|17|19|
|semitones from root |0| 2| 3| 5| 7| 8|10|
|name                |C| D|E♭| F| G|A♭|B♭|

```{ojs}
viewof play2 = scaleButton([0, 2, 3, 5, 7, 8, 10, 12])
```

The note names are always C, D, E, F, G, A, B. In order for the pitches to match, accidentals are added, always relative to the diatonic scale.

### All Modes of the Diatonic

We list the modes in an order that makes it easier to remember their relationship, rather than in order of their scale degrees.

| Mode | Starting scale degree | Notes | | | | | | | | |
|------|-----------------------|-------|-------|-|-|-|-|-|-|-|
| Lydian     | 4 | | C | D  |E   | F♯ | G  | A  | B  |<button class="btn btn-quarto" onclick="playScale([0,2,4,6,7,9,11,12]); return false;">Play</button>|
| Ionian     | 1 | | C | D  |E   | F  | G  | A  | B  |<button class="btn btn-quarto" onclick="playScale([0,2,4,5,7,9,11,12]); return false;">Play</button>|
| Mixolydian | 5 | | C | D  |E   | F  | G  | A  | B♭ |<button class="btn btn-quarto" onclick="playScale([0,2,4,5,7,9,10,12]); return false;">Play</button>|
| Dorian     | 2 | | C | D  |E♭  | F  | G  | A  | B♭ |<button class="btn btn-quarto" onclick="playScale([0,2,3,5,7,9,10,12]); return false;">Play</button>|
| Aeolian    | 6 | | C | D  |E♭  | F  | G  | A♭ | B♭ |<button class="btn btn-quarto" onclick="playScale([0,2,3,5,7,8,10,12]); return false;">Play</button>|
| Phrygian   | 3 | | C | D♭ | E♭ | F  | G  | A♭ | B♭ |<button class="btn btn-quarto" onclick="playScale([0,1,3,5,7,8,10,12]); return false;">Play</button>|
| Locrian    | 7 | | C | D♭ | E♭ | F  | G♭ | A♭ | B♭ |<button class="btn btn-quarto" onclick="playScale([0,1,3,5,6,8,10,12]); return false;">Play</button>|

In this order, then, there's an easy way to "see" how the fingerings relate to one another in an instrument with strings tuned in straight fourths. Say you're playing the bass. Then, if you're playing scales in A, these are the modes, in logical order.

#### Lydian
```{ojs}
scaleButton([0, 2, 4, 6, 7, 9, 11, 12], "Play Lydian")
```

```
 0 1 2 3 4 5 6
 -------------
G| |1| | | | |
D| |5| |6| |7|
A| |2| |3| |4|
E| | | | |1| |
 -------------
```

#### Ionian, flat the 4

```{ojs}
scaleButton([0, 2, 4, 5, 7, 9, 11, 12], "Play Ionian")
```

```
 0 1 2 3 4 5 6
 -------------
G| |1| | | | |
D| |5| |6| |7|
A| |2| |3|4| |
E| | | | |1| |
 -------------
```

#### Mixolydian, flat the 7:

```{ojs}
scaleButton([0, 2, 4, 5, 7, 9, 10, 12], "Play Mixolydian")
```

```
 0 1 2 3 4 5 6
 -------------
G| |1| | | | |
D| |5| |6|7| |
A| |2| |3|4| |
E| | | | |1| |
 -------------
```

#### Dorian, flat the 3:

```{ojs}
scaleButton([0, 2, 3, 5, 7, 9, 10, 12], "Play Dorian")
```

```
 0 1 2 3 4 5 6
 -------------
G| |1| | | | |
D| |5| |6|7| |
A| |2|3| |4| |
E| | | | |1| |
 -------------
```

#### Aeolian, flat the 6:

```{ojs}
scaleButton([0, 2, 3, 5, 7, 8, 10, 12], "Play Aeolian")
```

```
 0 1 2 3 4 5 6
 -------------
G| |1| | | | |
D| |5|6| |7| |
A| |2|3| |4| |
E| | | | |1| |
 -------------
```

#### Phrygian, flat the 2:

```{ojs}
scaleButton([0, 1, 3, 5, 7, 8, 10, 12], "Play Phrygian")
```

```
 0 1 2 3 4 5 6
 -------------
G| |1| | | | |
D| |5|6| |7| |
A|2| |3| |4| |
E| | | | |1| |
 -------------
```

#### Locrian, flat the 5:

```{ojs}
scaleButton([0, 1, 3, 5, 6, 8, 10, 12], "Play Locrian")
```

```
 0 1 2 3 4 5 6
 -------------
G| |1| | | | |
D|5| |6| |7| |
A|2| |3| |4| |
E| | | | |1| |
 -------------
```

It is much easier for me to see the changes in scales with this fingering, where the root (which is the one note that doesn't change on any of the modes) is played on separate strings.

## Harmonic Minor

Take the Aeolian (the "minor scale") and raise the 7 to a natural B

| Name           |   | | | | | | | |
|-|-|-|-|-|-|-|-|-|
| Aeolian        | C | D | E♭ | F | G | A♭ | B♭ |<button class="btn btn-quarto" onclick="playScale([0, 2, 3, 5, 7, 8, 10, 12]); return false;">Play</button>|
| Harmonic Minor | C | D | E♭ | F | G | A♭ | B  |<button class="btn btn-quarto" onclick="playScale([0, 2, 3, 5, 7, 8, 11, 12]); return false;">Play</button>|

The typical use of this scale is (like the name says) in harmony, so that you have a B next to the C, making chords that want to resolve to the I. But some people play it in melodies too, because it has a particular feel from the augmented second between A♭ and B.

### Modes

You can take modes of it too, and the fifth-degree mode of the harmonic minor is called the "Phrygian Dominant", presumably because it's the mode starting at the fifth ("dominant") scale degree of the harmonic minor, but it's very close to the Phrygian mode of the diatonic:

| Name | | | | | | | | |
|-|-|-|-|-|-|-|-|-|
| Phrygian Dominant | C | D♭ | E | F | G | A♭ | B♭ |<button class="btn btn-quarto" onclick="playScale([0, 1, 4, 5, 7, 8, 10, 12]); return false;">Play</button>|
| Phrygian | C | D♭ | E♭ | F | G | A♭ | B♭ |<button class="btn btn-quarto" onclick="playScale([0, 1, 3, 5, 7, 8, 10, 12]); return false;">Play</button>|

So it's almost exactly the Phrygian, but with a natural 3 instead of a flat 3.

## Altered (or superlocrian)

Take the modes of the diatonic scale, follow the pattern, and notice that the only "scale degree left to flatten" is the 4. That doesn't lead to a mode of the diatonic scale, but
leads to a useful scale, which is sometimes called the "superlocrian", or "altered":

| Name | | | | | | | | |
|-|-|-|-|-|-|-|-|-|
| Locrian      | C | D♭ | E♭ | F  | G♭ | A♭ | B♭ |<button class="btn btn-quarto" onclick="playScale([0,1,3,5,6,8,10,12]); return false;">Play</button>|
| Superlocrian | C | D♭ | E♭ | F♭ | G♭ | A♭ | B♭ |<button class="btn btn-quarto" onclick="playScale([0,1,3,4,6,8,10,12]); return false;">Play</button>|

I can see a couple of ways to think about it. One is that it plays like "Ionian with a sharp 1". The other comes from inspecting the intervals. It's HWHWWWW, so the first four notes are the first half of the 8-note diminished scale (the "half whole scale"), and the last three notes are the second half of the whole-note scale.

## Diminished Scale

The diminished scale is an _8_-note scale, built by alternating whole and half steps.
It only has two modes: starting on whole steps, and starting on half steps. It must be called the diminished scale because every triad chord is diminished, and every "seventh" chord is a dim7. It hass got "period 3", so it's symmetric around minor third transpositions, exactly like the (full) diminished 7 chord.

Because it has 8 notes, it's hard to match them with 7-scale note names directly.

Consider the diminished H-W scale in C. In integer notation, we have (0, 1, 3, 4, 6, 7, 9, 10, 12). How do we give the notes in this scale names? Clearly we'll have to repeat _some_ of the note names.

But which? Here's an idea. First we try to match all the pitches that exist in the diatonic scale:

| 0 | 1 | 3 | 4 | 6 | 7 | 9 | 10 | 12 |
| C |   |   | E |   | G | A |    | C  |

Then the ones there are left will have the same name, but with accidentals:

| 0 | 1 | 3 | 4 | 6 | 7 | 9 | 10 | 12 |
| C |   |   | E |   | G | A |    | C  |
| C | Db | D# | E | F# | G | A | Bb | C |

I've heard some musicians use this naming style (talking about how the HW scale has a flat ninth and a sharp ninth, eg).

Then for the WH scale, we get

| 0 | 2 | 3  | 5 | 6  | 8  | 9 | 11 | 12 |
| C | D | Eb | F | Gb | G# | A |  B | C  |

This naming makes sense to me because it gives the triad chord names of C a diminished triad. But I guess diminished note names are a bit of a sham anyway, because calling the diminished seventh "diminished" seems a bit of shoehorning to make the names "triadic". 

| Name | |
|-|-|
| H-W |<button class="btn btn-quarto" onclick="playScale([0,1,3,4,6,7,9,10,12]); return false;">Play</button>|
| W-H |<button class="btn btn-quarto" onclick="playScale([0,2,3,5,6,8,9,11,12]); return false;">Play</button>|


```{ojs}
//| output: false
import { playNote } from "/src/audio/karplus-strong.js"
import { makePlayer } from "/src/audio/audio.js";
import { notes } from "/src/audio/notes.js";
import { playScale } from "./scales.ts";

// this is ugly, but easily the most convenient way to do it
window.playScale = (...args) => {
    initPlayer();
    playScale(...args);
};

function initPlayer()
{
    if (window.player === undefined) {
        let player = makePlayer();
        window.player = player;
    }
}
function withPlayer(fun) {
    return () => {
        initPlayer();
        fun();
    }
}

function scaleButton(scale, label) {
    return Inputs.button(label || "Play", { value: 0, reduce: withPlayer(() => {
        playScale(scale);        
    })})
}

```
