---
title: "2024-01-02"
categories:
  - victory
---


This was a super generous first of biomes, with hearts everywhere to be found on the first couple of biomes, and All-Seeing Eye.
The Firebolt starting spell let me cheese the first orb up the mountain as well. I made it to the Snowy Depths with 250 health or so, which as it turns out made the rest of the run possible.

There were plenty of wands available but no great spells, so I was squeaking by on the Hiisi base with Glowing Lance and Firebolt for hitting big enemies. 
I had a broken wand to try and upgrade at the base, but I got attritioned out of the biome before I was able to get to the upgrade station.

When I got to the Jungle, I was clearly pretty underpowered and was mostly teleporting back to the Holy Mountain to replace spells/wands with anything I could find.
With no good immunities and just Phasing for protection, I decided to just risk going
down as fast as I could. 
At the Jungle Holy Mountain I finally found Repulsion Field. 
That, combined with 4 or 5 Black Hole spells let me just drill down as fast as I could, and skip the Vault and Temple of the Art.

- Final wand: trigger + quadruple random projectiles
- Run time: 1h01.
- Notable perks: All-Seeing Eye (still busted), Extra Perk, Projectile Repulsion Field