---
title: "2024-01-08"
date: 2024-01-08
categories:
  - defeat
  - skill-issue
---

Ghosts still bite you when you're invisible.

(I didn't take notes on this one, so it's from memory.)

I found effectively nothing on the first three or four biomes except for some black holes and an Invisiblium potion.
I found no hearts and had no way to heal. I almost died a couple of times and I was so desperate that I skipped
the healing heart a couple of times in the hopes that I would be able to go back to it later.

I actually managed to do that, and I was slowly making progress by black holing my way
back to the previous level, then going back into the Holy Mountain, healing, refreshing spells and going back down.

By the time I got to the Vault I had no real plan besides "hide with invisibility and hope for the best".
Turns out that actually worked well; I found an excellent wand right at the beginning of the Temple of the Art,
and all I needed to do was to get to the boss. I was low on health and so I was still cheesing the Temple
with Invisiblium.

But then in my head I somehow confused "invisible" with "invulnerable" and I walked into a ghost.

- Died: bitten to death at the Temple of the Art, having walked into a ghost.