---
title: "Karplus-Strong Plucked-String Synthesis"
format: html
bibliography:
  - music.bib
code-tools: false
echo: false
code-fold: false
css:
  - karplus-strong.css
date: 2022-06-01
---

::: {.column-page}

<div id="piano"></div>

:::

```{ojs}
//| output: false
import { init } from "/src/audio/karplus-strong.js"
import { init as initPiano } from "/src/audio/piano.js"

ojsPiano = {
  if (window._initEverything)
    return;
  window.d3 = d3;
  window._initEverything = true;
  initPiano();
  d3.select("#piano")
    .select("svg")
    .attr("viewBox", `0 0 960 400`)
    .attr("width", "100%")
    .attr("height", null);
  await new Promise((res) => {
    init(res);
  });
}

spectrogramArray = {
  ojsPiano;
  return Generators.observe(next => {
    const newData = (array) => {
      next(array);
    }
    window.player.spectrogram(newData, { fftSize: 32768 });
  });
}

function findPeaks(array)
{
  const result = [];
  for (let i = 1; i < array.length -1; ++i) {
    if (array[i] > array[i-1] && array[i] > array[i+1]) {
      result.push({i, v: array[i]});
    }
  }
  return result;
}

peaks = findPeaks(spectrogramArray)
  .filter(v => v.v > -60)
  .map(v => ({ freq: v.i * (48000 / 32768), amplitude: v.v }));
```

:::{.column-page}

```{ojs}
sizedPlot({
  marks: [
    Plot.line(
      peaks.map(v => [{ freq: v.freq, amplitude: -60 }, v, {freq: NaN, amplitude: NaN}]).flat(), 
      {
        x: "freq",
        y: "amplitude",
        clip: true
      }
    )
  ],
  y: { domain: [-60, -30], label: "amplitude (dB)" },
  x: { domain: [10, 10000], label: "frequency (Hz)" },
  height: 200,
  width: 800,
});
```

:::

Strings in stringed instruments make _harmonic_ sounds: each string produces not only a base frequency but a mix of sounds of different frequencies. A "harmonic" sound means simply that the frequencies of such a sound are always integer multiples of the base frequency. Typical western music features predominantly harmonic sounds, and such harmonic sounds account for much of western music's notion of [consonance and dissonance](consonance-and-dissonance.qmd). So if we want to synthesize musical instruments that can be used to create western-sounding music, we better be able to create sounds with lots of harmonic tones.

A plucking or hammering sound starts percussive and non-harmonic, but quickly resolves into a base frequency and lots of harmonic overtones. The higher the frequency, the faster these harmonics decay, and on long sustains we're left with only the low harmonics. Modeling this on slow computers used to be a significant challenge, until in 1983 Karplus and Strong devised a very simple method that sounds great to this day [@karplus1983digital].


## Appendix

### Code

```{ojs}
import { sizePlot } from "/src/cscheid/cscheid/observable.js";
function sizedPlot(...args) {
  const result = Plot.plot(...args);
  return sizePlot(result);
}
```