on:
  push:
    branches: main
  
  # TODO test PR trigger
  # pull_request:
  #   branches: main
  workflow_dispatch:

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Publish to GitHub Pages (and render)
        uses: cscheid/quarto-actions/publish@v2
        with:
          to: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

