on:
  push:
    branches: main
  
  # TODO test PR trigger
  # pull_request:
  #   branches: main

name: Render and deploy to Netlify

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up Quarto
        uses: cscheid/quarto-actions/setup
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      - name: Publish to Netlify (and render)
        uses: cscheid/quarto-actions/publish
        with:
          to: netlify
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}